name: tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ "8.2", "8.3", "8.4" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          coverage: xdebug
      - name: Install Composer dependencies
        run: composer update -q
      - name: Test
        run: vendor/bin/phpunit
      - name: Code Coverage
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: build/logs/clover.xml
